name: development build and push docker image to ghcr.io

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/practice-api

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
  auto-tagging:
    name: auto-tagging
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GHCR_ACCESS_TOKEN }}
          release_branches: develop
          tag_prefix: dev
          custom_release_rules: Feat:minor:Features,Bug:patch:Bugs,Chore:patch:Chores,Hotfix:patch
      - name: Create a Github release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.output.changelog }}
  push:
    name: push-image
    if: github.ref_type == 'tag'
    runs-on: ubuntu-20.04
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: Extract metadata (tag, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=dev{{version}}
            type=semver,pattern=dev{{major}}.{{minor}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.dev
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
